name: Reusable Release-Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git checkout -b new-release

    - name: Make changes to pull request
      run: date +%s > report.txt

    - name: Configure Git
      run: |
        git add .
        git commit -m "test"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:      
        commit-message: Prepare next development iteration
        branch: new-release
        delete-branch: true
        title: Prepare next development iteration
        body: Prepare next development iteration            
        assignees: ${{ github.actor }}
